In [3]:
import numpy as np
import pandas as pd
import random as rd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,roc_auc_score,plot_roc_curve,confusion_matrix,classification_report
from sklearn.metrics import multilabel_confusion_matrix
import math


In [4]:
df=pd.read_csv("D:\\academics\\SEM-V\\ML LAB\\Lab9(ANN)\\heart.csv")
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [5]:
y = df['output']
x = df.drop(['output'], axis = 1)

In [6]:
slr=StandardScaler()
x=slr.fit_transform(x)
x

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3)

In [8]:
MLP=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000)
MLP.fit(x_train,y_train)
y_pred=MLP.predict(x_test)
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [9]:
matrix=confusion_matrix(y_test,y_pred)
matrix

array([[34, 11],
       [12, 44]], dtype=int64)

In [10]:
#sns.heatmap(matrix,annot=True,cmap="Blues",fmt="d")

In [11]:
print("accuracy score: ",accuracy_score(y_test,y_pred))
print("report: \n",classification_report(y_test,y_pred))

accuracy score:  0.7722772277227723
report: 
               precision    recall  f1-score   support

           0       0.74      0.76      0.75        45
           1       0.80      0.79      0.79        56

    accuracy                           0.77       101
   macro avg       0.77      0.77      0.77       101
weighted avg       0.77      0.77      0.77       101

