In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:

irisdata = pd.read_csv(r"D:/academics/SEM-V/ML LAB/Lab7(SVM)/Iris.csv")
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
irisdata.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
X = irisdata.iloc[:, :-1].values
y = irisdata.iloc[:, -1].values

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [17]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [18]:
y_pred = svclassifier.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 7  0  0]
 [ 3  7  0]
 [ 0  0 13]]
0.9


In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       0.70      1.00      0.82         7
Iris-versicolor       1.00      0.70      0.82        10
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           0.90        30
      macro avg       0.90      0.90      0.88        30
   weighted avg       0.93      0.90      0.90        30

